### ISSUE TITLE
error code(s)

### ISSUE THREAD

**Issue by users789** [lownignitus/DingAnnouncer#1] opened 2018-09-03 23:38 UTC
Date: 2018-09-03 16:24:43
ID: 1
Error occured in: Global
Count: 3
Message: ..\AddOns\dingannouncer\dingannouncer.lua line 458:
   attempt to index global 'daSettings' (a nil value)
Debug:
   dingannouncer\dingannouncer.lua:458: daAuto()
   dingannouncer\dingannouncer.lua:511: ?()
   ..\FrameXML\ChatFrame.lua:4734: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4396: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4432: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'daSettings' (a nil value)"

Date: 2018-09-03 16:25:13
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\dingannouncer\dingannouncer.lua line 310:
   attempt to index global 'daSettings' (a nil value)
Debug:
   dingannouncer\dingannouncer.lua:310: daChatFunc()
   dingannouncer\dingannouncer.lua:516: ?()
   ..\FrameXML\ChatFrame.lua:4734: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4396: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4432: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
curLevel = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'daSettings' (a nil value)"
ding = "no"
curXp = 0
perCount = 0
message = ""
reported = true

AddOns:
  Swatter, v7.7.6095 (SwimmingSeadragon)
  Armory, vv15.0.1
  ArmoryGuildBank, vv15.0.1
  AucAdvanced, v7.7.6112 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6081 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6083 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6087 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6084 (SwimmingSeadragon)
  AucStatSimple, v7.7.6085 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6086 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6088 (SwimmingSeadragon)
  AutoGratzer, v2.0.2
  AutoRepair, v
  BagBrother, v
  Bagnon, v8.0.3
  BagnonConfig, v8.0.3
  BagnonCurrencies, v1.0.0
  BagnonScrap, v19
  BeanCounter, v7.7.6110 (SwimmingSeadragon)
  DBMCore, v8.0.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  dingannouncer, vv1.0.7
  Enchantrix, v7.7.6104 (SwimmingSeadragon)
  FBTitan, v1.0.15
  FishingBuddy, v1.9.15
  FlightMapEnhanced, v3.0.15
  GatherMate2, v1.43.3
  Grail, v097
  GrailAchievements, v011
  GrailQuestsenUS, v27178
  GrailReputations, v007
  GTFO, v4.46.4
  Informant, v7.7.6092 (SwimmingSeadragon)
  Outfitter, v5.20.3
  Pawn, v2.2.27
  QuestPointer, vv21
  Scrap, v13.10
  ScrapOptions, v13.10
  Simulationcraft, v1.10.6
  SlideBar, v7.7.6093 (SwimmingSeadragon)
  Stubby, v7.7.6094 (SwimmingSeadragon)
  Talented, vv2.0.0-Release
  Titan, v5.14.6.80000
  TitanBag, v5.14.6.80000
  TitanClock, v5.14.6.80000
  TitanCurrency, v8.0.B
  TitanGold, v5.14.6.80000
  TitanGuild, v8.0.0.0
  TitanLocation, v5.14.6.80000
  TitanLootType, v5.14.6.80000
  TitanMail, v7.35
  TitanMount, v8.0.0
  TitanPerformance, v5.14.6.80000
  TitanReloadUI, v1.0
  TitanRepair, v5.14.6.80000
  TitanVolume, v5.14.6.80000
  TitanXP, v5.14.6.80000
  TomTom, vv80001-1.0.2
  Wholly, v068
  WorldQuestsList, v79
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=702)

**Comment by lownignitus** [comment] 2018-09-03 23:44
any other info? like what were you doing? I am not sure what is going on here. As the variable should be initialized in the .toc itself, meaning it should be defined.

I have also been using this addon almost daily since launch and havent ran into this. So I would like more into so I can try and see if it is replicatable.

**Comment by lownignitus** [comment] 2018-09-04 00:07
By the looks of this you are trying to do something, idk what, with the chat slash commands for the addon. What can you tell me that you were trying to do?

**Comment by users789** [comment] 2018-09-04 00:28
I was trying to get the auto to trigger, each time I did options it just gave me the list of auto etc.  Also it does  NOT show up in the interface addons to do any configuring.  ( it does show up in the addons list, but not in the interface to do any configuring).  I was trying to set the options, then after that turn it auto on to ding my level  change, but no interface commands etc. So other then that no idea.  i was not attacking or anything. I just downloaded it and did a full relog and still just that.

**Comment by jimkillian** [comment] 2018-09-06 19:09
Sames issues here. The only thing I can get it to do is list the command options. When I do "/da auto on" it doesn't do anything ─ and DOES NOT announce my leveling! "/da options" does nothing at all.

**Comment by lownignitus** [comment] 2018-09-07 01:58
Well 1. @jimkillian the slash commands do not work like that "auto" is the toggle command. Exactly as I wrote it in the command list using "auto" toggles the command and setting itself. The reason "/da auto on" is not working, is because the addon does not recognize that as a command for it to use and respond to it. 

As to the rest, Im going to have to install WoW fresh on the wifes pc and load only Da so I can try and see if I can replicate these issues. MY working copy is running just fine, no bug reports at all.

**Comment by jimkillian** [comment] 2018-09-07 08:03
When I only put in "/da auto" it appeared to not even take the command, as in not even clearing the line as if it was entered, so I added "on" to see if that helped. I obviously didn't. Yes, I read the instructions and tried to follow them, but it appeared to do nothing so I gave something else a shot.

None of the things I tried had any effect other than repeating the command instructions.

**Comment by lownignitus** [comment] 2018-09-07 19:16
While I did find a slew of smaller bugs within the code itself, I cannot reproduce these errors as reported. I did some code cleanup and fixing I am going to be pushing it as v1.1.0. I would like you to try and do a clean install of this update and see if this fixes things for you. 

By clean I mean completely delete the old folder for DingAnnouncer and then installing the new v1.1.0. After you do that and do not change any of the code in the files, please launch the game and test out the new updates.

Also, would be a good idea, for debugging purposes, please disable all other addons and confirm that Ding Announcer is working fully on its own before testing with other addons. If you then get issues and/or errors after it is working on its own, this means there is a conflict with another addon that needs to be either reported to that addon dev team, or I need to rework my code to allow it to integrate properly with other addons.

**Comment by lownignitus** [comment] 2018-09-07 20:22
v1.1.1 has all the updates. I missed implementing new chat message system everywhere

**Comment by jimkillian** [comment] 2018-09-08 08:32
OK, I completely deleted the addons folder and created a new one. I went to Twitch, which showed NO installed addons, and installed **Ding Announcer** and then ran WoW.

Back in the original UI (which I find very unhelpful) I typed **/da** and got the standard list of options. I typed **/da auto** and the cursor didn't even move, sitting there at the end of the line. I hit enter again, no change.

I typed **/da advert** and hit enter and the text just stayed there on the line. Same thing when I typed **/da report**.

Something different happened when when I typed **/da options**, and the line went away as expected and _**NOTHING ELSE HAPPENED**_.


Doesn't look like any other addons are interfering, since no other addons are running.

Now I'm going to go back to installing everything and recreating my layout so that I can play the game. Guess I'll have to manually announce when I ding.

**Comment by lownignitus** [comment] 2018-09-08 08:44
To be clear, I only asked you to delete Ding Announcer, nothing else. Disabling means to just press the Addpon button on the character selection screen and make sure only DA was checked.... Anything you did beyond that is not my fault. Disabling all addons but the one you are having issues with is a standard practice for trying to pin down issues.

And which version of DA where you running? DA v1.1.1 is what i worked on and published today. I can even link you to a VOD on my Twitch where I did so for about 3 hours today live. I can assure you I made sure it was throughly working. I even leveled toons for an additional 2 hrs to further confirm, also in the VOD. I really am at a loss as to why you are having issues.

**Comment by lownignitus** [comment] 2018-09-08 08:45
Also the lack of Lua error codes is not helping either. When the chat commands are hanging and the chat typing box does not close, the game should display an error frame with additional info.

**Comment by jimkillian** [comment] 2018-09-08 09:15
But it doesn't display an error frame. I don't know what to do about that.

This is the one I installed with Twitch:
![image](https://user-images.githubusercontent.com/34056285/45252536-ccb20b80-b30c-11e8-9e4c-d64e19c37a0f.png)

**Comment by jimkillian** [comment] 2018-09-08 09:18
... and I'm sorry, but WOWDB Profiler keeps getting installed even when I delete the folder, so I assume something's running on my PC. I didn't notice it before.

**Comment by lownignitus** [comment] 2018-09-08 09:22
Again, Im not asking you to delete the "Interface" nor the "Addon" folder. I was asking you to just delete the "dingannouncer" folder, the one for the addon itself. That is known as doing a 'fresh install' and was just something I was wanting to see if it would help resolve any issues. 

And hmm I am guessing either have a setting set to disable display of Lua errors, or Blizzard has that turned off by default now. IDK, But good to know I guess.

**Comment by lownignitus** [comment] 2018-09-08 09:33
![image](https://user-images.githubusercontent.com/6155100/45252679-75616a80-b30f-11e8-9e2f-30d79609562b.png)

thats where I was meaning to enable or disable all other addons.

**Comment by lownignitus** [comment] 2018-09-08 11:33
And on wifes pc on fresh new install, Im having issue of the InterfaceOptionsFrame not freating the Addon Options, since they are not being created there are no options to view, and the auto command throws an error because there are not checkbuttons for it to change the state of, as they were never created. 

I am going to have to sleep on this and see what I can figure out. I also have Network Security homework that must come first as well.

**Comment by jimkillian** [comment] 2018-09-08 23:09
Just running through my garrison mine and noticed bug sack is red. Nowhere near leveling (53.2%) and not doing anything I would expect to interact with DA. This is the only bug from the current session:

78x dingannouncer\dingannouncer-v1.1.1.lua:303: attempt to index global 'daSettings' (a nil value)
dingannouncer\dingannouncer-v1.1.1.lua:303: in function `?'
dingannouncer\dingannouncer-v1.1.1.lua:27: in function <dingannouncer\dingannouncer.lua:26>

Locals:
self = <unnamed> {
 0 = <userdata>
 ADDON_LOADED = <function> defined @dingannouncer\dingannouncer.lua:30
 PLAYER_LEVEL_UP = <function> defined @dingannouncer\dingannouncer.lua:293
 PLAYER_XP_UPDATE = <function> defined @dingannouncer\dingannouncer.lua:301
 PLAYER_ENTERING_WORLD = <function> defined @dingannouncer\dingannouncer.lua:289
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'daSettings' (a nil value)"
curLevel = 0

**Comment by lownignitus** [comment] 2018-09-09 01:24
I seems there is a naming conflict  being caused by fact curse is repackaging the AddOn with name as all lowercase. I need to see if i can fix this, and would explain why the global saved character variables are not being initialized, ad not accessible. "attempt to index global 'daSettings' (a nil value)"

I will work on fixing this and push a fixed update.  Only took hours of hair pulling to figure out this basic of an issue -.-

**Comment by lownignitus** [comment] 2018-09-12 19:34
Pleas elet me know if the update I just pushed fixed your issues.

**Comment by jimkillian** [comment] 2018-09-13 10:22
**Yay!** All of the commands I tried worked and so did the option panel. I'm at 88% through level 111, so only another 100K or so XP to find out if it actually announces my ding.

Thanks for all the effort!

**Closed as completed** 2019-01-12 06:12 UTC
Labels: question, verifying
